/*
 * Constants for KM.
 */

import { type TagType, type TagTypeNum } from '../types/tag.js';

export const externalDatabases = [
	'anilist',
	'myanimelist',
	'kitsu'
];

export const supportedFiles = {
	video: [
		'avi',
		'mkv',
		'mp4',
		'webm',
		'mov',
		'wmv',
		'mpg',
		'm2ts',
		'rmvb',
		'ts',
		'm4v',
	],
	audio: [
		'ogg',
		'opus',
		'aac',
		'm4a',
		'mp3',
		'wav',
		'flac',
		'mid',
		'mka',
		'ogx'
	],
	lyrics: [
		'ass',
		'srt',
		'kar',
		'txt',
		'kfn',
		'lrc',
		'vtt',
		'sub',
		'sbv',
		'smi',
		'ssa',
		'json',
		'kbp'
	],
	mpvlyrics: [
		'ass',
		'jss',
		'lrc',
		'mpl2',
		'rt',
		'smi',
		'srt',
		'stl',
		'sub',
		'vtt'
	],
	pictures: [
		'jpg',
		'jpeg',
		'png',
		'gif',
		'webp',
		'apng',
		'jng'
	]
};

/** Regexps for validation. */
export const userRegexp = /^[a-zA-Z0-9_.-]*$/;
export const uuidRegexp =
	/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
export const uuidPlusTypeRegexp =
	/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}~[0-9]+$/;
export const md5Regexp = '^[a-f0-9]{32}$';
export const mediaFileRegexp = new RegExp(
	`^.+\\.(${supportedFiles.video.concat(supportedFiles.audio).join('|')})$`
);
export const imageFileRegexp = new RegExp(`^.+\\.(${supportedFiles.pictures.join('|')})$`);
export const backgroundFileRegexp = new RegExp(
	`^.+\\.(${supportedFiles.video.concat(supportedFiles.pictures).join('|')})$`
);
export const subFileRegexp = new RegExp(
	`^.+\\.(${supportedFiles.lyrics.join('|')})$`
);
export const audioFileRegexp = new RegExp(
	`^.+\\.(${supportedFiles.audio.join('|')})$`
);
export const hostnameRegexp = /^([a-zA-Z0-9-.]+\.[a-zA-Z0-9-]+)|(localhost:[0-9]+)$/;
export const asciiRegexp = /^[\u0000-\u007F]+$/u;
export const imageFileTypes = ['jpg', 'jpeg', 'png', 'gif'];
export const bools = [true, false, 'true', 'false', undefined];

export function getTagTypeName(type: TagTypeNum): TagType {
	return (<TagType[]>Object.keys(tagTypes)).find(
		t => tagTypes[t] === type
	) as TagType;
}

export const userTypes = Object.freeze({
	admin: 0,
	maintainer: 0.5,
	contributor: 0.6,
	user: 1,
	guest: 2,
});

export const tagTypes = Object.freeze({
	series: 1,
	singers: 2,
	songtypes: 3,
	creators: 4,
	langs: 5,
	authors: 6,
	misc: 7,
	songwriters: 8,
	groups: 9,
	families: 10,
	origins: 11,
	genres: 12,
	platforms: 13,
	versions: 14,
	warnings: 15,
	collections: 16,
	singergroups: 17,
	franchises: 18,
});

export const tagTypesKaraFileV4Order = Object.freeze({
	authors: 6,
	collections: 16,
	creators: 4,
	families: 10,
	genres: 12,
	groups: 9,
	langs: 5,
	misc: 7,
	origins: 11,
	platforms: 13,
	series: 1,
	singers: 2,
	singergroups: 17,
	songtypes: 3,
	songwriters: 8,
	versions: 14,
	warnings: 15,
	franchises: 18,
});

export const myanimelistStatusWatching = 1;
export const myanimelistStatusCompleted = 2;
export const myanimelistStatusOnHold = 3;
export const myanimelistStatusDropped = 4;
export const myanimelistStatusPlanToWatch = 5;

export const playlistMediaTypes = [
	'Sponsors',
	'Intros',
	'Outros',
	'Jingles',
	'Encores',
];

// Codecs supported by ffmpeg.
// To list them when upgrading to new ffmpeg versions :
// for codec in $(ffmpeg -codecs | grep -E '^.{3}V.*' | grep -v "=" | awk -F\  {'print $2'}) ; do echo "'$codec',"; done
// Replace the V in the first grep by S for subtitles or A for audio

export const supportedVideoCodecs = [
	'012v',
	'4xm',
	'8bps',
	'a64_multi',
	'a64_multi5',
	'aasc',
	'aic',
	'alias_pix',
	'amv',
	'anm',
	'ansi',
	'apng',
	'asv1',
	'asv2',
	'aura',
	'aura2',
	'av1',
	'avrn',
	'avrp',
	'avs',
	'avui',
	'ayuv',
	'bethsoftvid',
	'bfi',
	'binkvideo',
	'bintext',
	'bmp',
	'bmv_video',
	'brender_pix',
	'c93',
	'cavs',
	'cdgraphics',
	'cdxl',
	'cfhd',
	'cinepak',
	'clearvideo',
	'cljr',
	'cllc',
	'cmv',
	'cpia',
	'cscd',
	'cyuv',
	'daala',
	'dds',
	'dfa',
	'dirac',
	'dnxhd',
	'dpx',
	'dsicinvideo',
	'dvvideo',
	'dxa',
	'dxtory',
	'dxv',
	'escape124',
	'escape130',
	'exr',
	'ffv1',
	'ffvhuff',
	'fic',
	'flashsv',
	'flashsv2',
	'flic',
	'flv1',
	'fmvc',
	'fraps',
	'frwu',
	'g2m',
	'gif',
	'h261',
	'h263',
	'h263i',
	'h263p',
	'h264',
	'hap',
	'hevc',
	'hnm4video',
	'hq_hqa',
	'hqx',
	'huffyuv',
	'idcin',
	'idf',
	'iff_ilbm',
	'indeo2',
	'indeo3',
	'indeo4',
	'indeo5',
	'interplayvideo',
	'jpeg2000',
	'jpegls',
	'jv',
	'kgv1',
	'kmvc',
	'lagarith',
	'ljpeg',
	'loco',
	'm101',
	'mad',
	'magicyuv',
	'mdec',
	'mimic',
	'mjpeg',
	'mjpegb',
	'mmvideo',
	'motionpixels',
	'mpeg1video',
	'mpeg2video',
	'mpeg4',
	'mpegvideo_xvmc',
	'msa1',
	'msmpeg4v1',
	'msmpeg4v2',
	'msmpeg4v3',
	'msrle',
	'mss1',
	'mss2',
	'msvideo1',
	'mszh',
	'mts2',
	'mvc1',
	'mvc2',
	'mxpeg',
	'nuv',
	'paf_video',
	'pam',
	'pbm',
	'pcx',
	'pgm',
	'pgmyuv',
	'pictor',
	'pixlet',
	'png',
	'ppm',
	'prores',
	'psd',
	'ptx',
	'qdraw',
	'qpeg',
	'qtrle',
	'r10k',
	'r210',
	'rawvideo',
	'rl2',
	'roq',
	'rpza',
	'rscc',
	'rv10',
	'rv20',
	'rv30',
	'rv40',
	'sanm',
	'scpr',
	'screenpresso',
	'sgi',
	'sgirle',
	'sheervideo',
	'smackvideo',
	'smc',
	'smvjpeg',
	'snow',
	'sp5x',
	'speedhq',
	'sunrast',
	'svq1',
	'svq3',
	'targa',
	'targa_y216',
	'tdsc',
	'tgq',
	'tgv',
	'theora',
	'thp',
	'tiertexseqvideo',
	'tiff',
	'tmv',
	'tqi',
	'truemotion1',
	'truemotion2',
	'truemotion2rt',
	'tscc',
	'tscc2',
	'txd',
	'ulti',
	'utvideo',
	'v210',
	'v210x',
	'v308',
	'v408',
	'v410',
	'vb',
	'vble',
	'vc1',
	'vc1image',
	'vcr1',
	'vixl',
	'vmdvideo',
	'vmnc',
	'vp3',
	'vp5',
	'vp6',
	'vp6a',
	'vp6f',
	'vp7',
	'vp8',
	'vp9',
	'webp',
	'wmv1',
	'wmv2',
	'wmv3',
	'wmv3image',
	'wnv1',
	'wrapped_avframe',
	'ws_vqa',
	'xan_wc3',
	'xan_wc4',
	'xbin',
	'xbm',
	'xface',
	'xpm',
	'xwd',
	'y41p',
	'ylc',
	'yop',
	'yuv4',
	'zerocodec',
	'zlib',
	'zmbv',
];

export const supportedVideoColorSpaces = [
	// ffmpeg -pix_fmts | awk -F ' ' '{ printf "'\''%s'\'',\n", $2 }'
	'yuv420p',
	'yuyv422',
	'rgb24',
	'bgr24',
	'yuv422p',
	'yuv444p',
	'yuv410p',
	'yuv411p',
	'gray',
	'monow',
	'monob',
	'pal8',
	'yuvj420p',
	'yuvj422p',
	'yuvj444p',
	'uyvy422',
	'uyyvyy411',
	'bgr8',
	'bgr4',
	'bgr4_byte',
	'rgb8',
	'rgb4',
	'rgb4_byte',
	'nv12',
	'nv21',
	'argb',
	'rgba',
	'abgr',
	'bgra',
	'gray16be',
	'gray16le',
	'yuv440p',
	'yuvj440p',
	'yuva420p',
	'rgb48be',
	'rgb48le',
	'rgb565be',
	'rgb565le',
	'rgb555be',
	'rgb555le',
	'bgr565be',
	'bgr565le',
	'bgr555be',
	'bgr555le',
	'vaapi',
	'yuv420p16le',
	'yuv420p16be',
	'yuv422p16le',
	'yuv422p16be',
	'yuv444p16le',
	'yuv444p16be',
	'dxva2_vld',
	'rgb444le',
	'rgb444be',
	'bgr444le',
	'bgr444be',
	'ya8',
	'bgr48be',
	'bgr48le',
	'yuv420p9be',
	'yuv420p9le',
	'yuv420p10be',
	'yuv420p10le',
	'yuv422p10be',
	'yuv422p10le',
	'yuv444p9be',
	'yuv444p9le',
	'yuv444p10be',
	'yuv444p10le',
	'yuv422p9be',
	'yuv422p9le',
	'gbrp',
	'gbrp9be',
	'gbrp9le',
	'gbrp10be',
	'gbrp10le',
	'gbrp16be',
	'gbrp16le',
	'yuva422p',
	'yuva444p',
	'yuva420p9be',
	'yuva420p9le',
	'yuva422p9be',
	'yuva422p9le',
	'yuva444p9be',
	'yuva444p9le',
	'yuva420p10be',
	'yuva420p10le',
	'yuva422p10be',
	'yuva422p10le',
	'yuva444p10be',
	'yuva444p10le',
	'yuva420p16be',
	'yuva420p16le',
	'yuva422p16be',
	'yuva422p16le',
	'yuva444p16be',
	'yuva444p16le',
	'vdpau',
	'xyz12le',
	'xyz12be',
	'nv16',
	'nv20le',
	'nv20be',
	'rgba64be',
	'rgba64le',
	'bgra64be',
	'bgra64le',
	'yvyu422',
	'ya16be',
	'ya16le',
	'gbrap',
	'gbrap16be',
	'gbrap16le',
	'qsv',
	'mmal',
	'd3d11va_vld',
	'cuda',
	'0rgb',
	'rgb0',
	'0bgr',
	'bgr0',
	'yuv420p12be',
	'yuv420p12le',
	'yuv420p14be',
	'yuv420p14le',
	'yuv422p12be',
	'yuv422p12le',
	'yuv422p14be',
	'yuv422p14le',
	'yuv444p12be',
	'yuv444p12le',
	'yuv444p14be',
	'yuv444p14le',
	'gbrp12be',
	'gbrp12le',
	'gbrp14be',
	'gbrp14le',
	'yuvj411p',
	'bayer_bggr8',
	'bayer_rggb8',
	'bayer_gbrg8',
	'bayer_grbg8',
	'bayer_bggr16le',
	'bayer_bggr16be',
	'bayer_rggb16le',
	'bayer_rggb16be',
	'bayer_gbrg16le',
	'bayer_gbrg16be',
	'bayer_grbg16le',
	'bayer_grbg16be',
	'xvmc',
	'yuv440p10le',
	'yuv440p10be',
	'yuv440p12le',
	'yuv440p12be',
	'ayuv64le',
	'ayuv64be',
	'videotoolbox_vld',
	'p010le',
	'p010be',
	'gbrap12be',
	'gbrap12le',
	'gbrap10be',
	'gbrap10le',
	'mediacodec',
	'gray12be',
	'gray12le',
	'gray10be',
	'gray10le',
	'p016le',
	'p016be',
	'd3d11',
	'gray9be',
	'gray9le',
	'gbrpf32be',
	'gbrpf32le',
	'gbrapf32be',
	'gbrapf32le',
	'drm_prime',
	'opencl',
	'gray14be',
	'gray14le',
	'grayf32be',
	'grayf32le',
	'yuva422p12be',
	'yuva422p12le',
	'yuva444p12be',
	'yuva444p12le',
	'nv24',
	'nv42',
	'vulkan',
	'y210be',
	'y210le',
	'x2rgb10le',
	'x2rgb10be',
	'x2bgr10le',
	'x2bgr10be',
	'p210be',
	'p210le',
	'p410be',
	'p410le',
	'p216be',
	'p216le',
	'p416be',
	'p416le',
];

export const supportedAudioCodecs = [
	'4gv',
	'8svx_exp',
	'8svx_fib',
	'aac',
	'aac_latm',
	'ac3',
	'adpcm_4xm',
	'adpcm_adx',
	'adpcm_afc',
	'adpcm_aica',
	'adpcm_ct',
	'adpcm_dtk',
	'adpcm_ea',
	'adpcm_ea_maxis_xa',
	'adpcm_ea_r1',
	'adpcm_ea_r2',
	'adpcm_ea_r3',
	'adpcm_ea_xas',
	'adpcm_g722',
	'adpcm_g726',
	'adpcm_g726le',
	'adpcm_ima_amv',
	'adpcm_ima_apc',
	'adpcm_ima_dat4',
	'adpcm_ima_dk3',
	'adpcm_ima_dk4',
	'adpcm_ima_ea_eacs',
	'adpcm_ima_ea_sead',
	'adpcm_ima_iss',
	'adpcm_ima_oki',
	'adpcm_ima_qt',
	'adpcm_ima_rad',
	'adpcm_ima_smjpeg',
	'adpcm_ima_wav',
	'adpcm_ima_ws',
	'adpcm_ms',
	'adpcm_mtaf',
	'adpcm_psx',
	'adpcm_sbpro_2',
	'adpcm_sbpro_3',
	'adpcm_sbpro_4',
	'adpcm_swf',
	'adpcm_thp',
	'adpcm_thp_le',
	'adpcm_vima',
	'adpcm_xa',
	'adpcm_yamaha',
	'alac',
	'amr_nb',
	'amr_wb',
	'ape',
	'atrac1',
	'atrac3',
	'atrac3al',
	'atrac3p',
	'atrac3pal',
	'avc',
	'binkaudio_dct',
	'binkaudio_rdft',
	'bmv_audio',
	'celt',
	'comfortnoise',
	'cook',
	'dsd_lsbf',
	'dsd_lsbf_planar',
	'dsd_msbf',
	'dsd_msbf_planar',
	'dsicinaudio',
	'dss_sp',
	'dst',
	'dts',
	'dvaudio',
	'eac3',
	'evrc',
	'flac',
	'g723_1',
	'g729',
	'gsm',
	'gsm_ms',
	'iac',
	'ilbc',
	'imc',
	'interplay_dpcm',
	'interplayacm',
	'mace3',
	'mace6',
	'metasound',
	'mlp',
	'mp1',
	'mp2',
	'mp3',
	'mp3adu',
	'mp3on4',
	'mp4als',
	'musepack7',
	'musepack8',
	'nellymoser',
	'opus',
	'paf_audio',
	'pcm_alaw',
	'pcm_bluray',
	'pcm_dvd',
	'pcm_f16le',
	'pcm_f24le',
	'pcm_f32be',
	'pcm_f32le',
	'pcm_f64be',
	'pcm_f64le',
	'pcm_lxf',
	'pcm_mulaw',
	'pcm_s16be',
	'pcm_s16be_planar',
	'pcm_s16le',
	'pcm_s16le_planar',
	'pcm_s24be',
	'pcm_s24daud',
	'pcm_s24le',
	'pcm_s24le_planar',
	'pcm_s32be',
	'pcm_s32le',
	'pcm_s32le_planar',
	'pcm_s64be',
	'pcm_s64le',
	'pcm_s8',
	'pcm_s8_planar',
	'pcm_u16be',
	'pcm_u16le',
	'pcm_u24be',
	'pcm_u24le',
	'pcm_u32be',
	'pcm_u32le',
	'pcm_u8',
	'pcm_zork',
	'qcelp',
	'qdm2',
	'qdmc',
	'ra_144',
	'ra_288',
	'ralf',
	'roq_dpcm',
	's302m',
	'sdx2_dpcm',
	'shorten',
	'sipr',
	'smackaudio',
	'smv',
	'sol_dpcm',
	'sonic',
	'sonicls',
	'speex',
	'tak',
	'truehd',
	'truespeech',
	'tta',
	'twinvq',
	'vmdaudio',
	'vorbis',
	'voxware',
	'wavesynth',
	'wavpack',
	'westwood_snd1',
	'wmalossless',
	'wmapro',
	'wmav1',
	'wmav2',
	'wmavoice',
	'xan_dpcm',
	'xma1',
	'xma2',
];

export const supportedAudioChannelLayouts = [
	// ffmpeg -layouts
	'mono',            // FC
	'stereo',          // FL+FR
	'2.1',             // FL+FR+LFE
	'3.0',             // FL+FR+FC
	'3.0(back)',       // FL+FR+BC
	'4.0',             // FL+FR+FC+BC
	'quad',            // FL+FR+BL+BR
	'quad(side)',      // FL+FR+SL+SR
	'3.1',             // FL+FR+FC+LFE
	'5.0',             // FL+FR+FC+BL+BR
	'5.0(side)',       // FL+FR+FC+SL+SR
	'4.1',             // FL+FR+FC+LFE+BC
	'5.1',             // FL+FR+FC+LFE+BL+BR
	'5.1(side)',       // FL+FR+FC+LFE+SL+SR
	'6.0',             // FL+FR+FC+BC+SL+SR
	'6.0(front)',      // FL+FR+FLC+FRC+SL+SR
	'hexagonal',       // FL+FR+FC+BL+BR+BC
	'6.1',             // FL+FR+FC+LFE+BC+SL+SR
	'6.1(back)',       // FL+FR+FC+LFE+BL+BR+BC
	'6.1(front)',      // FL+FR+LFE+FLC+FRC+SL+SR
	'7.0',             // FL+FR+FC+BL+BR+SL+SR
	'7.0(front)',      // FL+FR+FC+FLC+FRC+SL+SR
	'7.1',             // FL+FR+FC+LFE+BL+BR+SL+SR
	'7.1(wide)',       // FL+FR+FC+LFE+BL+BR+FLC+FRC
	'7.1(wide-side)',  // FL+FR+FC+LFE+FLC+FRC+SL+SR
	'7.1(top)',        // FL+FR+FC+LFE+BL+BR+TFL+TFR
	'octagonal',       // FL+FR+FC+BL+BR+BC+SL+SR
	'cube',            // FL+FR+BL+BR+TFL+TFR+TBL+TBR
	'hexadecagonal',   // FL+FR+FC+BL+BR+BC+SL+SR+TFL+TFC+TFR+TBL+TBC+TBR+WL+WR
	'downmix',         // DL+DR
	'22.2'
] as const;
export type AudioChannelLayout = typeof supportedAudioChannelLayouts[number];

// Video encoder specific params
export const videoEncoderParamMap = {
	libx264: ['-preset', 'slow'],
	libx265: ['-preset', 'slow'],
	libsvtav1: ['-preset', '2'],
};

// Audio VBR parameters differ between audio encoders, map the best quality for each one
export const audioVbrParamsMap = {
	libmp3lame: ['-qscale:a', '2'], // Values 0-9, where 0-3 are transparent (good) and 4+ noticable (worse)
	libfdk_aac: ['-vbr', '5'], // Values 0-5, where 5 is best
	libopus: ['-vbr', 'on', '-compression_level', '10', '-b:a', '196k'],
};

// CRF value for video differs between encoders, map the optimal start for each one
export const crfStartValueMap = {
	libx264: 18,
	libx265: 22,
	libsvtav1: 25,
};

// Map codecs to available encoders
export function getEncoderMap(ffmpegCapabilities: string) {
	return {
		opus: 'libopus',
		vorbis: 'libvorbis',
		av1: 'libsvtav1',
		aac: ffmpegCapabilities.includes('libfdk-aac') ? 'libfdk_aac' : 'aac',
		mp3: 'libmp3lame',
		h264: 'libx264',
		h265: 'libx265',
		hevc: 'libx265',
	};
}
